import uuid

import pendulum

from src.common.config import get_settings
from src.common.db import execute_sql, fetch_one
from src.common.logger import get_logger
from src.extract.gbfs_client import GBFSClient
from src.load.station_status_raw_loader import load_station_status_raw
from src.metadata.pipeline_run_tracker import (
    finish_pipeline_run_failed,
    finish_pipeline_run_success,
    start_pipeline_run,
)
from src.metadata.watermark_manager import update_watermark
from src.quality.station_status_checks import run_station_status_dq_checks
from src.transform.station_status_transformer import (
    transform_station_status,
    transform_station_vehicle_type_status,
)

logger = get_logger(__name__)


def cleanup_existing_batch_records(batch_id: str) -> None:
    """
    Clean existing raw and staging records for the same batch_id.

    This makes the smoke test safer if the same batch_id is reused.
    In normal smoke test execution, batch_id is generated from UUID,
    so duplicate batch_id is unlikely, but this cleanup keeps the logic
    consistent with the Airflow DAG.
    """
    logger.info(f"Cleaning existing records for batch_id={batch_id}")

    deleted_vehicle_type_status = execute_sql(
        """
        DELETE FROM staging.station_vehicle_type_status
        WHERE batch_id = :batch_id
        """,
        {
            "batch_id": batch_id,
        },
    )

    deleted_station_status = execute_sql(
        """
        DELETE FROM staging.station_status
        WHERE batch_id = :batch_id
        """,
        {
            "batch_id": batch_id,
        },
    )

    deleted_raw = execute_sql(
        """
        DELETE FROM raw.station_status_snapshots
        WHERE batch_id = :batch_id
          AND feed_name = 'station_status'
        """,
        {
            "batch_id": batch_id,
        },
    )

    logger.info(
        f"Cleanup completed for batch_id={batch_id}: "
        f"staging.station_vehicle_type_status={deleted_vehicle_type_status}, "
        f"staging.station_status={deleted_station_status}, "
        f"raw.station_status_snapshots={deleted_raw}"
    )


def get_station_status_watermark_value(batch_id: str) -> str:
    """
    Get watermark value from staging.station_status.

    Watermark priority:
    1. MAX(source_last_updated)
    2. MAX(last_reported)
    3. MAX(fetched_at)
    4. current UTC timestamp as fallback
    """
    watermark_row = fetch_one(
        """
        SELECT
            MAX(source_last_updated) AS max_source_updated,
            MAX(last_reported) AS max_last_reported,
            MAX(fetched_at) AS max_fetched
        FROM staging.station_status
        WHERE batch_id = :batch_id
        """,
        {
            "batch_id": batch_id,
        },
    )

    watermark_value = None

    if watermark_row:
        if watermark_row["max_source_updated"]:
            watermark_value = watermark_row["max_source_updated"].isoformat()
        elif watermark_row["max_last_reported"]:
            watermark_value = watermark_row["max_last_reported"].isoformat()
        elif watermark_row["max_fetched"]:
            watermark_value = watermark_row["max_fetched"].isoformat()

    if not watermark_value:
        watermark_value = pendulum.now("UTC").isoformat()

    return watermark_value


def get_rejected_record_count(run_id: str) -> int:
    """
    Count rejected records generated by this smoke test run.
    """
    rejected_row = fetch_one(
        """
        SELECT COUNT(*) AS rejected_count
        FROM etl_metadata.rejected_records
        WHERE run_id = :run_id
          AND source_name = 'gbfs_station_status'
        """,
        {
            "run_id": run_id,
        },
    )

    if rejected_row and rejected_row["rejected_count"] is not None:
        return int(rejected_row["rejected_count"])

    return 0


def run_station_status_smoke_test() -> None:
    """
    Smoke test for the complete GBFS station_status ETL lifecycle.

    Flow:
    Start tracking
    -> cleanup current batch
    -> extract station_status feed
    -> load raw snapshots
    -> transform staging tables
    -> run data quality checks
    -> update smoke-test watermark
    -> finish tracking
    """
    settings = get_settings()

    dag_id = "test_station_status_smoke"
    run_id = f"manual-ss-smoke-{uuid.uuid4()}"
    batch_id = run_id

    logger.info(
        f"Initializing station_status smoke test. "
        f"dag_id={dag_id}, run_id={run_id}, batch_id={batch_id}"
    )

    try:
        # 1. Start pipeline run tracking
        start_pipeline_run(
            run_id=run_id,
            dag_id=dag_id,
        )

        # 2. Cleanup raw and staging records for the current batch_id
        cleanup_existing_batch_records(batch_id)

        # 3. Extract station_status feed
        client = GBFSClient(settings.GBFS_BASE_URL)

        logger.info("Fetching station_status feed from GBFS API...")
        payload = client.fetch_feed("station_status")

        # 4. Load raw station_status snapshots
        raw_loaded = load_station_status_raw(
            payload=payload,
            batch_id=batch_id,
            run_id=run_id,
            language=settings.GBFS_LANGUAGE,
        )

        if raw_loaded <= 0:
            raise RuntimeError("No raw station_status records were loaded.")

        logger.info(
            f"Raw station_status snapshots loaded successfully. "
            f"raw_loaded={raw_loaded}"
        )

        # 5. Transform raw -> staging
        transformed_status = transform_station_status(batch_id)
        transformed_vehicle_types = transform_station_vehicle_type_status(batch_id)

        if transformed_status <= 0:
            raise RuntimeError(
                "No staging.station_status records were transformed."
            )

        total_staging_loaded = transformed_status + transformed_vehicle_types

        logger.info(
            f"Station_status transform completed. "
            f"station_status={transformed_status}, "
            f"vehicle_type_status={transformed_vehicle_types}, "
            f"total_staging_loaded={total_staging_loaded}"
        )

        # 6. Run Data Quality checks
        run_station_status_dq_checks(
            run_id=run_id,
            batch_id=batch_id,
        )

        logger.info("Station_status data quality checks completed successfully.")

        # 7. Extract and update smoke-test watermark
        watermark_value = get_station_status_watermark_value(batch_id)

        # Use a smoke-test-specific source name to avoid modifying
        # the real production pipeline watermark.
        update_watermark(
            source_name="gbfs_station_status_smoke_test",
            last_successful_value=watermark_value,
        )

        # 8. Count rejected records and mark pipeline run as success
        records_rejected = get_rejected_record_count(run_id)

        finish_pipeline_run_success(
            run_id=run_id,
            records_extracted=1,
            records_loaded=total_staging_loaded,
            records_rejected=records_rejected,
        )

        logger.info("==========================================================")
        logger.info("Station Status Smoke Test Summary:")
        logger.info(f"  - Run ID: {run_id}")
        logger.info(f"  - Batch ID: {batch_id}")
        logger.info(f"  - Raw snapshots loaded: {raw_loaded}")
        logger.info(f"  - Staging station status loaded: {transformed_status}")
        logger.info(
            f"  - Staging vehicle type status loaded: {transformed_vehicle_types}"
        )
        logger.info(f"  - Rejected records: {records_rejected}")
        logger.info(f"  - Updated smoke-test watermark: {watermark_value}")
        logger.info("==========================================================")
        logger.info("Station Status ETL smoke test completed successfully.")

    except Exception as e:
        logger.error(f"Station Status ETL smoke test failed: {e}")

        finish_pipeline_run_failed(
            run_id=run_id,
            error_message=str(e),
        )

        raise


if __name__ == "__main__":
    run_station_status_smoke_test()